#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezRota.VeriKatmani
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbTezliRota")]
	public partial class dbTezRotaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttArac(tArac instance);
    partial void UpdatetArac(tArac instance);
    partial void DeletetArac(tArac instance);
    partial void InserttAracTipi(tAracTipi instance);
    partial void UpdatetAracTipi(tAracTipi instance);
    partial void DeletetAracTipi(tAracTipi instance);
    partial void InserttNokta(tNokta instance);
    partial void UpdatetNokta(tNokta instance);
    partial void DeletetNokta(tNokta instance);
    partial void InserttOptimizasyonEmir(tOptimizasyonEmir instance);
    partial void UpdatetOptimizasyonEmir(tOptimizasyonEmir instance);
    partial void DeletetOptimizasyonEmir(tOptimizasyonEmir instance);
    partial void InserttPlan(tPlan instance);
    partial void UpdatetPlan(tPlan instance);
    partial void DeletetPlan(tPlan instance);
    partial void InserttTasima(tTasima instance);
    partial void UpdatetTasima(tTasima instance);
    partial void DeletetTasima(tTasima instance);
    #endregion
		
		public dbTezRotaDataContext() : 
				base(global::TezRota.Properties.Settings.Default.dbTezliRotaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbTezRotaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTezRotaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTezRotaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbTezRotaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tArac> tAracs
		{
			get
			{
				return this.GetTable<tArac>();
			}
		}
		
		public System.Data.Linq.Table<tAracTipi> tAracTipis
		{
			get
			{
				return this.GetTable<tAracTipi>();
			}
		}
		
		public System.Data.Linq.Table<tNokta> tNoktas
		{
			get
			{
				return this.GetTable<tNokta>();
			}
		}
		
		public System.Data.Linq.Table<tOptimizasyonEmir> tOptimizasyonEmirs
		{
			get
			{
				return this.GetTable<tOptimizasyonEmir>();
			}
		}
		
		public System.Data.Linq.Table<tPlan> tPlans
		{
			get
			{
				return this.GetTable<tPlan>();
			}
		}
		
		public System.Data.Linq.Table<tTasima> tTasimas
		{
			get
			{
				return this.GetTable<tTasima>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tArac")]
	public partial class tArac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DorsePlaka;
		
		private string _CekiciPlaka;
		
		private int _AracTipId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDorsePlakaChanging(string value);
    partial void OnDorsePlakaChanged();
    partial void OnCekiciPlakaChanging(string value);
    partial void OnCekiciPlakaChanged();
    partial void OnAracTipIdChanging(int value);
    partial void OnAracTipIdChanged();
    #endregion
		
		public tArac()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DorsePlaka", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DorsePlaka
		{
			get
			{
				return this._DorsePlaka;
			}
			set
			{
				if ((this._DorsePlaka != value))
				{
					this.OnDorsePlakaChanging(value);
					this.SendPropertyChanging();
					this._DorsePlaka = value;
					this.SendPropertyChanged("DorsePlaka");
					this.OnDorsePlakaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CekiciPlaka", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CekiciPlaka
		{
			get
			{
				return this._CekiciPlaka;
			}
			set
			{
				if ((this._CekiciPlaka != value))
				{
					this.OnCekiciPlakaChanging(value);
					this.SendPropertyChanging();
					this._CekiciPlaka = value;
					this.SendPropertyChanged("CekiciPlaka");
					this.OnCekiciPlakaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AracTipId", DbType="Int NOT NULL")]
		public int AracTipId
		{
			get
			{
				return this._AracTipId;
			}
			set
			{
				if ((this._AracTipId != value))
				{
					this.OnAracTipIdChanging(value);
					this.SendPropertyChanging();
					this._AracTipId = value;
					this.SendPropertyChanged("AracTipId");
					this.OnAracTipIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tAracTipi")]
	public partial class tAracTipi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Kod;
		
		private string _Ad;
		
		private string _AracTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKodChanging(string value);
    partial void OnKodChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnAracTuruChanging(string value);
    partial void OnAracTuruChanged();
    #endregion
		
		public tAracTipi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AracTuru", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AracTuru
		{
			get
			{
				return this._AracTuru;
			}
			set
			{
				if ((this._AracTuru != value))
				{
					this.OnAracTuruChanging(value);
					this.SendPropertyChanging();
					this._AracTuru = value;
					this.SendPropertyChanged("AracTuru");
					this.OnAracTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tNokta")]
	public partial class tNokta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _nokta_isim;
		
		private string _kordinat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onnokta_isimChanging(string value);
    partial void Onnokta_isimChanged();
    partial void OnkordinatChanging(string value);
    partial void OnkordinatChanged();
    #endregion
		
		public tNokta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nokta_isim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nokta_isim
		{
			get
			{
				return this._nokta_isim;
			}
			set
			{
				if ((this._nokta_isim != value))
				{
					this.Onnokta_isimChanging(value);
					this.SendPropertyChanging();
					this._nokta_isim = value;
					this.SendPropertyChanged("nokta_isim");
					this.Onnokta_isimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kordinat", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string kordinat
		{
			get
			{
				return this._kordinat;
			}
			set
			{
				if ((this._kordinat != value))
				{
					this.OnkordinatChanging(value);
					this.SendPropertyChanging();
					this._kordinat = value;
					this.SendPropertyChanged("kordinat");
					this.OnkordinatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tOptimizasyonEmir")]
	public partial class tOptimizasyonEmir : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _PlanId;
		
		private System.DateTime _EmirZamani;
		
		private string _Skor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPlanIdChanging(int value);
    partial void OnPlanIdChanged();
    partial void OnEmirZamaniChanging(System.DateTime value);
    partial void OnEmirZamaniChanged();
    partial void OnSkorChanging(string value);
    partial void OnSkorChanged();
    #endregion
		
		public tOptimizasyonEmir()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanId", DbType="Int NOT NULL")]
		public int PlanId
		{
			get
			{
				return this._PlanId;
			}
			set
			{
				if ((this._PlanId != value))
				{
					this.OnPlanIdChanging(value);
					this.SendPropertyChanging();
					this._PlanId = value;
					this.SendPropertyChanged("PlanId");
					this.OnPlanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmirZamani", DbType="DateTime NOT NULL")]
		public System.DateTime EmirZamani
		{
			get
			{
				return this._EmirZamani;
			}
			set
			{
				if ((this._EmirZamani != value))
				{
					this.OnEmirZamaniChanging(value);
					this.SendPropertyChanging();
					this._EmirZamani = value;
					this.SendPropertyChanged("EmirZamani");
					this.OnEmirZamaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skor", DbType="NVarChar(MAX)")]
		public string Skor
		{
			get
			{
				return this._Skor;
			}
			set
			{
				if ((this._Skor != value))
				{
					this.OnSkorChanging(value);
					this.SendPropertyChanging();
					this._Skor = value;
					this.SendPropertyChanged("Skor");
					this.OnSkorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tPlan")]
	public partial class tPlan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _PlanIsmi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPlanIsmiChanging(string value);
    partial void OnPlanIsmiChanged();
    #endregion
		
		public tPlan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanIsmi", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PlanIsmi
		{
			get
			{
				return this._PlanIsmi;
			}
			set
			{
				if ((this._PlanIsmi != value))
				{
					this.OnPlanIsmiChanging(value);
					this.SendPropertyChanging();
					this._PlanIsmi = value;
					this.SendPropertyChanged("PlanIsmi");
					this.OnPlanIsmiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTasima")]
	public partial class tTasima : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _PlanId;
		
		private int _TasimaTipi;
		
		private string _NakliyeNo;
		
		private int _SiraId;
		
		private int _KaynakId;
		
		private int _HedefId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPlanIdChanging(int value);
    partial void OnPlanIdChanged();
    partial void OnTasimaTipiChanging(int value);
    partial void OnTasimaTipiChanged();
    partial void OnNakliyeNoChanging(string value);
    partial void OnNakliyeNoChanged();
    partial void OnSiraIdChanging(int value);
    partial void OnSiraIdChanged();
    partial void OnKaynakIdChanging(int value);
    partial void OnKaynakIdChanged();
    partial void OnHedefIdChanging(int value);
    partial void OnHedefIdChanged();
    #endregion
		
		public tTasima()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanId", DbType="Int NOT NULL")]
		public int PlanId
		{
			get
			{
				return this._PlanId;
			}
			set
			{
				if ((this._PlanId != value))
				{
					this.OnPlanIdChanging(value);
					this.SendPropertyChanging();
					this._PlanId = value;
					this.SendPropertyChanged("PlanId");
					this.OnPlanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TasimaTipi", DbType="Int NOT NULL")]
		public int TasimaTipi
		{
			get
			{
				return this._TasimaTipi;
			}
			set
			{
				if ((this._TasimaTipi != value))
				{
					this.OnTasimaTipiChanging(value);
					this.SendPropertyChanging();
					this._TasimaTipi = value;
					this.SendPropertyChanged("TasimaTipi");
					this.OnTasimaTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NakliyeNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NakliyeNo
		{
			get
			{
				return this._NakliyeNo;
			}
			set
			{
				if ((this._NakliyeNo != value))
				{
					this.OnNakliyeNoChanging(value);
					this.SendPropertyChanging();
					this._NakliyeNo = value;
					this.SendPropertyChanged("NakliyeNo");
					this.OnNakliyeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiraId", DbType="Int NOT NULL")]
		public int SiraId
		{
			get
			{
				return this._SiraId;
			}
			set
			{
				if ((this._SiraId != value))
				{
					this.OnSiraIdChanging(value);
					this.SendPropertyChanging();
					this._SiraId = value;
					this.SendPropertyChanged("SiraId");
					this.OnSiraIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KaynakId", DbType="Int NOT NULL")]
		public int KaynakId
		{
			get
			{
				return this._KaynakId;
			}
			set
			{
				if ((this._KaynakId != value))
				{
					this.OnKaynakIdChanging(value);
					this.SendPropertyChanging();
					this._KaynakId = value;
					this.SendPropertyChanged("KaynakId");
					this.OnKaynakIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HedefId", DbType="Int NOT NULL")]
		public int HedefId
		{
			get
			{
				return this._HedefId;
			}
			set
			{
				if ((this._HedefId != value))
				{
					this.OnHedefIdChanging(value);
					this.SendPropertyChanging();
					this._HedefId = value;
					this.SendPropertyChanged("HedefId");
					this.OnHedefIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
